version: "3.8"

services:
  mariadb:
    image: mariadb:10.6
    container_name: erpnext-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  redis-cache:
    image: redis:7
    container_name: erpnext-redis-cache
    ports:
      - "6379:6379"

  redis-queue:
    image: redis:7
    container_name: erpnext-redis-queue
    ports:
      - "6380:6379"

  redis-socketio:
    image: redis:7
    container_name: erpnext-redis-socketio
    ports:
      - "6381:6379"

volumes:
  mariadb_data: